version: "3.9"

services:
  pr-sju-dash:
    build: .
    container_name: pr-sju-dash
    ports:
      - "8080:80"
    volumes:
      - ./profiles:/usr/share/nginx/html/profiles
      - ./data:/usr/share/nginx/html/data
    environment:
      - DEFAULT_PROFILE=PR-DIV
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
